### ISSUE TITLE
Text locale for messsages & buttons

### ISSUE THREAD

**Issue by erickjx** [r-hannuschka/ngx-fileupload#266]
Hi, i want replace  messages & buttons text to locale Spanish, but i saw the messages are directed in the code.

it possible change it on object creation?

**Comment by r-hannuschka** [comment]
Currently i did not have implement that, but sure i think it would be a good improvement, if you have any suggestions what would be a good way just tell me or create a pull request for that :)

Best Regards,
Ralf

**Comment by erickjx** [comment]
Can you implement [ngx-translate](https://github.com/ngx-translate/core)
```
<div>{{ 'Finish Download' | translate:messages.download.finish }}</div>
```
or Old fashion locale config like this:
```
this.storage = new NgxFileUploadStorage({
      autoStart: true,
      locale: {
        en: {
          toolbar: {
             upload: 'Upload',
             clear: 'Clear',
          },
         nextElement: ...
         messagess: {
            progressBarFinish: ....
         }
        },
        es: {
           ....
        }
     }
    });
```

**Comment by r-hannuschka** [comment]
I know what u want but the FileUploadStorage is only a storage wich contains all "Upload Requests". 

So there are 2 Packages for that now:

first is @ngx-file-upload/core which only contains business logic to serve Models, Services to create, handle Uploads.

second is @ngx-file-upload/ui which has predefined Components. The main Idea is you can only use @ngx-file-upload/core and put your own UI on top of that if you dont want to use the UI Components.

For example:

(Drop Zone)[https://r-hannuschka.github.io/ngx-fileupload/#/drop-zone]
(Customize)[https://r-hannuschka.github.io/ngx-fileupload/#/customize]

But yes i will take a look since @ngx-file-upload/ui has hard coded text labels for all Components, i will take a look on this but this i could to not before weekend. And Angular i18n sounds good.

**Comment by r-hannuschka** [comment]
- [ ] add language support
- [ ] update docs
- [ ] add unit tests

**Comment by r-hannuschka** [comment]
implemented as described above. You will find docs here: [Language Support](https://github.com/r-hannuschka/ngx-fileupload/blob/master/docs/ui/i18n.md)

**Comment by erickjx** [comment]
Thanks, excellent Work, only one fix in the title:

Ngx Fileuplad I18N  => Ngx Fileupload I18N

**Comment by r-hannuschka** [comment]
Ah thx i will create new issue for that, but it seems it is only an documentation bug currently :)

Glad u like it and thx for this improvement idea.

Best Regards,
Ralf
