### ISSUE TITLE
Running `ng xi18n` ends with error

### ISSUE THREAD

**Issue by psupina** [r-hannuschka/ngx-fileupload#364]
**Describe the bug**
When I import some module from the **@ngx-file-upload/ui** package, running `ng xi18n` ends with error:

`ERROR in Can't resolve all parameters for UploadViewComponent in .../node_modules/@ngx-file-upload/ui/ngx-file-upload-ui.d.ts: ([object Object], ?).`

**To Reproduce**
1. Create a new Angular 9.1 application
2. Run `npm i --save @ngx-file-upload/ui @ngx-file-upload/core`
3. Use these lines in the  app.module.ts file:

```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppComponent } from './app.component';
import { NgxFileUploadCoreModule } from '@ngx-file-upload/core';
import { NgxFileUploadUiFileBrowserModule } from '@ngx-file-upload/ui';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,

    NgxFileUploadCoreModule,
    NgxFileUploadUiFileBrowserModule,
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

4. Run `ng xi18n`
5. See these errors:

```
ERROR in Can't resolve all parameters for UploadViewComponent in .../node_modules/@ngx-file-upload/ui/ngx-file-upload-ui.d.ts: ([object Object], ?).
Can't resolve all parameters for ɵe in .../node_modules/@ngx-file-upload/ui/ngx-file-upload-ui.d.ts: (?).
Can't resolve all parameters for ɵf in .../node_modules/@ngx-file-upload/ui/ngx-file-upload-ui.d.ts: (?).
```

**Expected behavior**
Running `ng xi18n` should complete without errors.

**Desktop (please complete the following information):**
 - OS: Windows 10 (1909)
 - Node: v10.15.3
 - Angular: v9.1.12

**Comment by r-hannuschka** [comment]
Hey sry for late response, it seems this is broken with angular 9 there they introduced the ivy renderer. I can see this since all Pull Requests from renovate failing since angular 9 was introduced.

But currently i'm short of time to do this i will see how about the weekend to reanimate this repository.

**Comment by r-hannuschka** [comment]
So okay sry, not sure this is still a problem for you maybe you are not using @ngx-file-upload/core anymore ;)

Currently i upgrade to angular 12 and the error not seems to happens anymore, but i never used @angular/localization before because there was a show stopper like "you can't switch language without reloading the whole page"

Currently with angular 12 i see something like this:

```bash
C:\Users\Ralf\work\ngx-fileupload\src>ng xi18n
Warning: "ng xi18n" has been deprecated and will be removed in a future major version. Please use "ng extract-i18n" instead.
√ Browser application bundle generation complete.
```

seems to be okay only it is deprecated (okay) not an issue. Maybe i do the mistake and uploaded ivy before, now nearly 1 year later i got an npm error if i try to publish an library which has been build with ivy.

**Comment by psupina** [comment]
Thank you for the upgrade.
We are still using the Angular 9 version in the project, but we will need to upgrade to a newer version in the near future.

I have made a test on a new Angular 12 CLI application and it failed (because of strictNullChecks).
I have opened another issue here: #406

**Comment by r-hannuschka** [comment]
Yeah and no :D I just got punished by set strict to false, do not know if this will work now on angular 9 since typescript version has been changed and this could be also a breaking change.

Got this between 1.x and 2.0 typescript got an update and all types was wrong :(
